apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    app: {{ .Values.name }}
