apiVersion: v2
appVersion: "v0.87.1"
name: kube-prometheus-stack
description: Giant Swarm's Prometheus Operator Deployment
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
version: 19.0.1
home: https://github.com/giantswarm/kube-prometheus-stack-app
kubeVersion: ">=1.25.0-0"
maintainers:
  - name: giantswarm/team-atlas
    email: team-atlas@giantswarm.io
annotations:
  io.giantswarm.application.team: atlas
dependencies:
  - name: kube-prometheus-stack
    version: 80.4.1
    repository: https://prometheus-community.github.io/helm-charts
sources:
  - "https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack"
